version: '3'

services: 
  djangoapp:
    build: .
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    environment:
     - PYTHONUNBUFFERED=1
    command:  pipenv run python sistemita/manage.py behave sistemita/features