version: '3'

services: 
  db:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
  app:
    build: .
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    environment:
     - PYTHONUNBUFFERED=1
    command:  ./docker_entrypoint.sh
    depends_on:
      - db
