version: '3.7'

services:
  db:
    restart: always
    image: postgres:11.4-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sistemita
      - POSTGRES_PASSWORD=!RA7#DbGr4rUNjxb
      - POSTGRES_DB=sistemita
  app:
    restart: always
    build: .
    volumes: 
      - .:/app
    command: pipenv run gunicorn --workers 3 --bind :8000 sistemita.wsgi:application
    expose: 
      - 8000
    volumes:
      - ./static:/app/static/
      - ./media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env.production
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=daniel.padula@tutanota.com
      - URL=sistemita.liqueed.org
      - VALIDATION=http
      - TZ=America/Argentina/Buenos_Aires
      - PUID=0
      - PGID=0
  # nginx:
  #   restart: always
  #   image: nginx:stable-alpine
  #   volumes:
  #     - ./config/nginx/conf.d:/etc/nginx/conf.d
  #     - ./static:/static/
  #     - ./media:/media/
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - app
      
volumes:
  postgres_data:
  static:
  media:
